trigger:
  - main
  
pr: none

pool:
  name: "Default"

stages:
  - stage: Prisma_Scan
    displayName: "Run Prisma Checkov Scan"
    jobs:
      - job: Run_Checkov
        displayName: "Checkov Scan Job"
        steps:
          - script: |
              echo "API Key Debug: ${TOKEN_PRISMA:0:4}"
              ls -ltr
              pwd

              export PATH=$HOME/.local/bin:$PATH
              export PRISMA_API_URL="https://api.sg.prismacloud.io"

              checkov -d . \
                --use-enforcement-rules \
                --bc-api-key "$TOKEN_PRISMA" \
                --repo-id fir36/prisma_scan \
                --branch main \
                -o cli -o junitxml --output-file-path console,CheckovReport.xml || true
            displayName: "Run Checkov Scan"
