parameters:
  - name: environment
    displayName: Deployment environment
    type: string
  - name: stageName
    type: string
  - name: condition
    type: string
  - name: dockerNamespace
    displayName: Docker Namespace
    type: string
  - name: dockerRepository
    displayName: Docker Repository
    type: string

stages:
  - stage: ${{ parameters.stageName }}
    condition: ${{ parameters.condition }}
    displayName: Build and Test Docker Image for ${{ parameters.environment }}
    jobs:
      - job: build_and_test
        displayName: Build Docker Image and Validate Tag
        workspace:
          clean: all
        steps:
          - task: Docker@2
            displayName: "Build Docker Image"
            inputs:
              command: build
              repository: ${{ parameters.dockerNamespace }}/${{ parameters.dockerRepository }}
              dockerfile: ci/templates/Dockerfile
              tags: $(Build.SourceVersion)

          - task: Bash@3
              displayName: "Download Prisma Cloud twistcli"
              inputs:
                targetType: inline
                script: |
                  echo "Downloading Twistcli..."
                  curl -k -H "Authorization: Bearer ZbXJR+pmvB/DF1Q3uMEwtzjwc2U=" \
                    "https://api.sg.prismacloud.io/api/v1/util/twistcli" -o twistcli
                  chmod +x twistcli

          - task: Bash@3
            displayName: "Scan Docker Image with Twistcli"
            inputs:
              targetType: inline
              script: |
                echo "Scanning Docker Image..."
                ./twistcli images scan \
                  --address https://api.sg.prismacloud.io \
                  --token 14ce6bb4-8e4a-4a8d-86a3-a2490d7dcbd8::ZbXJR+pmvB/DF1Q3uMEwtzjwc2U= \
                  --details \
                  mabsg3dspmwcr1.azurecr.io/dsp-web:$(Build.SourceVersion)
