trigger:
- main  # or your specific branch

pr: none

pool:
  name: "Default"

variables:
- group: 'New variable group 04-Mar'  # Link to your variable group

stages:
- stage: PrintVariables
  displayName: 'Print Environment Variables'
  jobs:
  - job: PrintJob
    displayName: 'Print Variables from Variable Group'
    steps:
    - script: |
        echo "GITHUB_PAT: $(GITHUB_PAT)"
      displayName: 'Echo Variables'
